### PR TITLE
added compatibility functions for stream reader

### PR DESCRIPTION
**Pull request by cmilke**
This should allow any format version to be safely interpreted by the DataStreamReader. The EventValue class now contains all prior and current members it ever had. Each format version has its own payload parser, which assigns a value to every element of EventValue. Values that are not supported in a specific format version are set to -1.

### CODE REVIEW

**Comment by ruck314** [comment]
@cmilke: you submodule/surf does not match with master branch. Are your other branches uses the same surf submodule reference as master (which has a bug fix for phase locking to the external SMA reference)?
https://github.com/slaclab/surf/pull/477
https://github.com/slaclab/surf/tree/SI5345-bug-fix

**Comment by cmilke** [comment]
Development of that branch was done on my laptop (which is not at all used
for running the FPGAs). I believe the branches being used on the main pc
are using the appropriate submodules. I will confirm shortly, but the PLL
has been locking as we expect.

**Comment by cmilke** [comment]
Actually, discard this pull request. There is at least one silly typo in it, maybe more. I will send another request when I have debugged it

**Comment by ruck314** [comment]
@cmilke: you submodule/surf does not match with master branch. Are your other branches uses the same surf submodule reference as master (which has a bug fix for phase locking to the external SMA reference)?
https://github.com/slaclab/surf/pull/477

**Pull request closed without merging**
